// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CompressedMovieClip struct {
	_tab flatbuffers.Table
}

func GetRootAsCompressedMovieClip(buf []byte, offset flatbuffers.UOffsetT) *CompressedMovieClip {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CompressedMovieClip{}
	x.Init(buf, n+offset)
	return x
}

func FinishCompressedMovieClipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCompressedMovieClip(buf []byte, offset flatbuffers.UOffsetT) *CompressedMovieClip {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CompressedMovieClip{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCompressedMovieClipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CompressedMovieClip) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CompressedMovieClip) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CompressedMovieClip) Id() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *CompressedMovieClip) ExportNameRefId() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *CompressedMovieClip) MutateExportNameRefId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *CompressedMovieClip) Framerate() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateFramerate(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *CompressedMovieClip) FramesCount() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateFramesCount(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *CompressedMovieClip) UnknownBool() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateUnknownBool(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *CompressedMovieClip) ChildrenIds(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *CompressedMovieClip) ChildrenIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateChildrenIds(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *CompressedMovieClip) ChildrenNameRefIds(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *CompressedMovieClip) ChildrenNameRefIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateChildrenNameRefIds(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *CompressedMovieClip) ChildrenBlending(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *CompressedMovieClip) ChildrenBlendingLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CompressedMovieClip) ChildrenBlendingBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CompressedMovieClip) MutateChildrenBlending(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *CompressedMovieClip) Frames(obj *MovieClipFrame, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CompressedMovieClip) FramesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CompressedMovieClip) FrameElementsOffset() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *CompressedMovieClip) MutateFrameElementsOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *CompressedMovieClip) MatrixBankIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateMatrixBankIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *CompressedMovieClip) ScalingGridIndex() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *CompressedMovieClip) MutateScalingGridIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func (rcv *CompressedMovieClip) CompressedDataOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CompressedMovieClip) MutateCompressedDataOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(28, n)
}

func CompressedMovieClipStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func CompressedMovieClipAddId(builder *flatbuffers.Builder, id uint16) {
	builder.PrependUint16Slot(0, id, 0)
}
func CompressedMovieClipAddExportNameRefId(builder *flatbuffers.Builder, exportNameRefId uint32) {
	builder.PrependUint32(exportNameRefId)
	builder.Slot(1)
}
func CompressedMovieClipAddFramerate(builder *flatbuffers.Builder, framerate byte) {
	builder.PrependByteSlot(2, framerate, 0)
}
func CompressedMovieClipAddFramesCount(builder *flatbuffers.Builder, framesCount uint16) {
	builder.PrependUint16Slot(3, framesCount, 0)
}
func CompressedMovieClipAddUnknownBool(builder *flatbuffers.Builder, unknownBool byte) {
	builder.PrependByteSlot(4, unknownBool, 0)
}
func CompressedMovieClipAddChildrenIds(builder *flatbuffers.Builder, childrenIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(childrenIds), 0)
}
func CompressedMovieClipStartChildrenIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func CompressedMovieClipAddChildrenNameRefIds(builder *flatbuffers.Builder, childrenNameRefIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(childrenNameRefIds), 0)
}
func CompressedMovieClipStartChildrenNameRefIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CompressedMovieClipAddChildrenBlending(builder *flatbuffers.Builder, childrenBlending flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(childrenBlending), 0)
}
func CompressedMovieClipStartChildrenBlendingVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CompressedMovieClipAddFrames(builder *flatbuffers.Builder, frames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(frames), 0)
}
func CompressedMovieClipStartFramesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func CompressedMovieClipAddFrameElementsOffset(builder *flatbuffers.Builder, frameElementsOffset uint32) {
	builder.PrependUint32(frameElementsOffset)
	builder.Slot(9)
}
func CompressedMovieClipAddMatrixBankIndex(builder *flatbuffers.Builder, matrixBankIndex uint32) {
	builder.PrependUint32Slot(10, matrixBankIndex, 0)
}
func CompressedMovieClipAddScalingGridIndex(builder *flatbuffers.Builder, scalingGridIndex uint32) {
	builder.PrependUint32(scalingGridIndex)
	builder.Slot(11)
}
func CompressedMovieClipAddCompressedDataOffset(builder *flatbuffers.Builder, compressedDataOffset uint32) {
	builder.PrependUint32Slot(12, compressedDataOffset, 0)
}
func CompressedMovieClipEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
