// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CompressedMovieClips struct {
	_tab flatbuffers.Table
}

func GetRootAsCompressedMovieClips(buf []byte, offset flatbuffers.UOffsetT) *CompressedMovieClips {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CompressedMovieClips{}
	x.Init(buf, n+offset)
	return x
}

func FinishCompressedMovieClipsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCompressedMovieClips(buf []byte, offset flatbuffers.UOffsetT) *CompressedMovieClips {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CompressedMovieClips{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCompressedMovieClipsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CompressedMovieClips) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CompressedMovieClips) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CompressedMovieClips) Movieclips(obj *CompressedMovieClip, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CompressedMovieClips) MovieclipsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CompressedMovieClipsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CompressedMovieClipsAddMovieclips(builder *flatbuffers.Builder, movieclips flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(movieclips), 0)
}
func CompressedMovieClipsStartMovieclipsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CompressedMovieClipsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
