// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExternalMatrixBanks struct {
	_tab flatbuffers.Table
}

func GetRootAsExternalMatrixBanks(buf []byte, offset flatbuffers.UOffsetT) *ExternalMatrixBanks {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExternalMatrixBanks{}
	x.Init(buf, n+offset)
	return x
}

func FinishExternalMatrixBanksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExternalMatrixBanks(buf []byte, offset flatbuffers.UOffsetT) *ExternalMatrixBanks {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExternalMatrixBanks{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExternalMatrixBanksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExternalMatrixBanks) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExternalMatrixBanks) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExternalMatrixBanks) Banks(obj *ExternalMatrixBank, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ExternalMatrixBanks) BanksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ExternalMatrixBanksStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ExternalMatrixBanksAddBanks(builder *flatbuffers.Builder, banks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(banks), 0)
}
func ExternalMatrixBanksStartBanksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ExternalMatrixBanksEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
