// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExternalMatrixBank struct {
	_tab flatbuffers.Table
}

func GetRootAsExternalMatrixBank(buf []byte, offset flatbuffers.UOffsetT) *ExternalMatrixBank {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExternalMatrixBank{}
	x.Init(buf, n+offset)
	return x
}

func FinishExternalMatrixBankBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsExternalMatrixBank(buf []byte, offset flatbuffers.UOffsetT) *ExternalMatrixBank {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExternalMatrixBank{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedExternalMatrixBankBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ExternalMatrixBank) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExternalMatrixBank) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExternalMatrixBank) Index() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ExternalMatrixBank) CompressedDataOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateCompressedDataOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ExternalMatrixBank) CompressedDataSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateCompressedDataSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *ExternalMatrixBank) DecompressedDataSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateDecompressedDataSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *ExternalMatrixBank) CompressedMatrixDataSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateCompressedMatrixDataSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *ExternalMatrixBank) ShortMatrixDataSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateShortMatrixDataSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *ExternalMatrixBank) ShortMatrixCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateShortMatrixCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *ExternalMatrixBank) FloatMatrixCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateFloatMatrixCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *ExternalMatrixBank) ColorTransformCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateColorTransformCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *ExternalMatrixBank) ClipDataOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateClipDataOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *ExternalMatrixBank) ClipDataSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateClipDataSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *ExternalMatrixBank) Unk2() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateUnk2(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func (rcv *ExternalMatrixBank) Unk3() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateUnk3(n uint32) bool {
	return rcv._tab.MutateUint32Slot(28, n)
}

func (rcv *ExternalMatrixBank) Unk4() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExternalMatrixBank) MutateUnk4(n uint32) bool {
	return rcv._tab.MutateUint32Slot(30, n)
}

func ExternalMatrixBankStart(builder *flatbuffers.Builder) {
	builder.StartObject(14)
}
func ExternalMatrixBankAddIndex(builder *flatbuffers.Builder, index uint32) {
	builder.PrependUint32Slot(0, index, 0)
}
func ExternalMatrixBankAddCompressedDataOffset(builder *flatbuffers.Builder, compressedDataOffset uint32) {
	builder.PrependUint32Slot(1, compressedDataOffset, 0)
}
func ExternalMatrixBankAddCompressedDataSize(builder *flatbuffers.Builder, compressedDataSize uint32) {
	builder.PrependUint32Slot(2, compressedDataSize, 0)
}
func ExternalMatrixBankAddDecompressedDataSize(builder *flatbuffers.Builder, decompressedDataSize uint32) {
	builder.PrependUint32Slot(3, decompressedDataSize, 0)
}
func ExternalMatrixBankAddCompressedMatrixDataSize(builder *flatbuffers.Builder, compressedMatrixDataSize uint32) {
	builder.PrependUint32Slot(4, compressedMatrixDataSize, 0)
}
func ExternalMatrixBankAddShortMatrixDataSize(builder *flatbuffers.Builder, shortMatrixDataSize uint32) {
	builder.PrependUint32Slot(5, shortMatrixDataSize, 0)
}
func ExternalMatrixBankAddShortMatrixCount(builder *flatbuffers.Builder, shortMatrixCount uint32) {
	builder.PrependUint32Slot(6, shortMatrixCount, 0)
}
func ExternalMatrixBankAddFloatMatrixCount(builder *flatbuffers.Builder, floatMatrixCount uint32) {
	builder.PrependUint32Slot(7, floatMatrixCount, 0)
}
func ExternalMatrixBankAddColorTransformCount(builder *flatbuffers.Builder, colorTransformCount uint32) {
	builder.PrependUint32Slot(8, colorTransformCount, 0)
}
func ExternalMatrixBankAddClipDataOffset(builder *flatbuffers.Builder, clipDataOffset uint32) {
	builder.PrependUint32Slot(9, clipDataOffset, 0)
}
func ExternalMatrixBankAddClipDataSize(builder *flatbuffers.Builder, clipDataSize uint32) {
	builder.PrependUint32Slot(10, clipDataSize, 0)
}
func ExternalMatrixBankAddUnk2(builder *flatbuffers.Builder, unk2 uint32) {
	builder.PrependUint32Slot(11, unk2, 0)
}
func ExternalMatrixBankAddUnk3(builder *flatbuffers.Builder, unk3 uint32) {
	builder.PrependUint32Slot(12, unk3, 0)
}
func ExternalMatrixBankAddUnk4(builder *flatbuffers.Builder, unk4 uint32) {
	builder.PrependUint32Slot(13, unk4, 0)
}
func ExternalMatrixBankEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
