// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileDescriptor struct {
	_tab flatbuffers.Table
}

func GetRootAsFileDescriptor(buf []byte, offset flatbuffers.UOffsetT) *FileDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileDescriptor{}
	x.Init(buf, n+offset)
	return x
}

func FinishFileDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFileDescriptor(buf []byte, offset flatbuffers.UOffsetT) *FileDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FileDescriptor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFileDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FileDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileDescriptor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileDescriptor) TranslationPrecision() Precision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Precision(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FileDescriptor) MutateTranslationPrecision(n Precision) bool {
	return rcv._tab.MutateUint32Slot(4, uint32(n))
}

func (rcv *FileDescriptor) ScalePrecision() Precision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Precision(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FileDescriptor) MutateScalePrecision(n Precision) bool {
	return rcv._tab.MutateUint32Slot(6, uint32(n))
}

func (rcv *FileDescriptor) ShapeCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateShapeCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *FileDescriptor) MovieClipsCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateMovieClipsCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *FileDescriptor) TextureCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateTextureCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *FileDescriptor) TextFieldsCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateTextFieldsCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *FileDescriptor) Unk3() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateUnk3(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *FileDescriptor) Unk4() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateUnk4(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *FileDescriptor) ResourcesOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateResourcesOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *FileDescriptor) TexturesLength() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateTexturesLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *FileDescriptor) Exports(obj *ExportNameHash, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FileDescriptor) ExportsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FileDescriptor) CompressedSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateCompressedSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func (rcv *FileDescriptor) ExternalMatrixBankSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileDescriptor) MutateExternalMatrixBankSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(28, n)
}

func FileDescriptorStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func FileDescriptorAddTranslationPrecision(builder *flatbuffers.Builder, translationPrecision Precision) {
	builder.PrependUint32Slot(0, uint32(translationPrecision), 0)
}
func FileDescriptorAddScalePrecision(builder *flatbuffers.Builder, scalePrecision Precision) {
	builder.PrependUint32Slot(1, uint32(scalePrecision), 0)
}
func FileDescriptorAddShapeCount(builder *flatbuffers.Builder, shapeCount uint32) {
	builder.PrependUint32Slot(2, shapeCount, 0)
}
func FileDescriptorAddMovieClipsCount(builder *flatbuffers.Builder, movieClipsCount uint32) {
	builder.PrependUint32Slot(3, movieClipsCount, 0)
}
func FileDescriptorAddTextureCount(builder *flatbuffers.Builder, textureCount uint32) {
	builder.PrependUint32Slot(4, textureCount, 0)
}
func FileDescriptorAddTextFieldsCount(builder *flatbuffers.Builder, textFieldsCount uint32) {
	builder.PrependUint32Slot(5, textFieldsCount, 0)
}
func FileDescriptorAddUnk3(builder *flatbuffers.Builder, unk3 uint32) {
	builder.PrependUint32Slot(6, unk3, 0)
}
func FileDescriptorAddUnk4(builder *flatbuffers.Builder, unk4 uint32) {
	builder.PrependUint32Slot(7, unk4, 0)
}
func FileDescriptorAddResourcesOffset(builder *flatbuffers.Builder, resourcesOffset uint32) {
	builder.PrependUint32Slot(8, resourcesOffset, 0)
}
func FileDescriptorAddTexturesLength(builder *flatbuffers.Builder, texturesLength uint32) {
	builder.PrependUint32Slot(9, texturesLength, 0)
}
func FileDescriptorAddExports(builder *flatbuffers.Builder, exports flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(exports), 0)
}
func FileDescriptorStartExportsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FileDescriptorAddCompressedSize(builder *flatbuffers.Builder, compressedSize uint32) {
	builder.PrependUint32Slot(11, compressedSize, 0)
}
func FileDescriptorAddExternalMatrixBankSize(builder *flatbuffers.Builder, externalMatrixBankSize uint32) {
	builder.PrependUint32Slot(12, externalMatrixBankSize, 0)
}
func FileDescriptorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
