// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"

	sc__flash__SC2__Typing "sc2fla/internal/sc/sc2fb/sc/flash/SC2/Typing"
)

type MatrixBank struct {
	_tab flatbuffers.Table
}

func GetRootAsMatrixBank(buf []byte, offset flatbuffers.UOffsetT) *MatrixBank {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MatrixBank{}
	x.Init(buf, n+offset)
	return x
}

func FinishMatrixBankBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMatrixBank(buf []byte, offset flatbuffers.UOffsetT) *MatrixBank {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MatrixBank{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMatrixBankBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MatrixBank) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MatrixBank) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MatrixBank) Matrices(obj *sc__flash__SC2__Typing.Matrix2x3, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 24
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MatrixBank) MatricesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MatrixBank) Colors(obj *sc__flash__SC2__Typing.ColorTransform, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 7
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MatrixBank) ColorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MatrixBank) HalfMatrices(obj *sc__flash__SC2__Typing.HalfMatrix2x3, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 12
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MatrixBank) HalfMatricesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MatrixBankStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MatrixBankAddMatrices(builder *flatbuffers.Builder, matrices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(matrices), 0)
}
func MatrixBankStartMatricesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(24, numElems, 4)
}
func MatrixBankAddColors(builder *flatbuffers.Builder, colors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(colors), 0)
}
func MatrixBankStartColorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(7, numElems, 1)
}
func MatrixBankAddHalfMatrices(builder *flatbuffers.Builder, halfMatrices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(halfMatrices), 0)
}
func MatrixBankStartHalfMatricesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(12, numElems, 2)
}
func MatrixBankEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
