// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClip struct {
	_tab flatbuffers.Table
}

func GetRootAsMovieClip(buf []byte, offset flatbuffers.UOffsetT) *MovieClip {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MovieClip{}
	x.Init(buf, n+offset)
	return x
}

func FinishMovieClipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMovieClip(buf []byte, offset flatbuffers.UOffsetT) *MovieClip {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MovieClip{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMovieClipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MovieClip) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClip) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MovieClip) Id() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovieClip) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *MovieClip) ExportNameRefId() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *MovieClip) MutateExportNameRefId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MovieClip) Framerate() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovieClip) MutateFramerate(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *MovieClip) FramesCount() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovieClip) MutateFramesCount(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *MovieClip) UnknownBool() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovieClip) MutateUnknownBool(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *MovieClip) ChildrenIds(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *MovieClip) ChildrenIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MovieClip) MutateChildrenIds(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func (rcv *MovieClip) ChildrenNameRefIds(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *MovieClip) ChildrenNameRefIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MovieClip) MutateChildrenNameRefIds(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *MovieClip) ChildrenBlending(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MovieClip) ChildrenBlendingLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MovieClip) ChildrenBlendingBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MovieClip) MutateChildrenBlending(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MovieClip) Frames(obj *MovieClipFrame, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MovieClip) FramesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MovieClip) FrameElementsOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 4294967295
}

func (rcv *MovieClip) MutateFrameElementsOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *MovieClip) MatrixBankIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MovieClip) MutateMatrixBankIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *MovieClip) ScalingGridIndex() *uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetUint32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *MovieClip) MutateScalingGridIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func (rcv *MovieClip) ShortFrames(obj *MovieClipShortFrame, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 2
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MovieClip) ShortFramesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MovieClipStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func MovieClipAddId(builder *flatbuffers.Builder, id uint16) {
	builder.PrependUint16Slot(0, id, 0)
}
func MovieClipAddExportNameRefId(builder *flatbuffers.Builder, exportNameRefId uint32) {
	builder.PrependUint32(exportNameRefId)
	builder.Slot(1)
}
func MovieClipAddFramerate(builder *flatbuffers.Builder, framerate byte) {
	builder.PrependByteSlot(2, framerate, 0)
}
func MovieClipAddFramesCount(builder *flatbuffers.Builder, framesCount uint16) {
	builder.PrependUint16Slot(3, framesCount, 0)
}
func MovieClipAddUnknownBool(builder *flatbuffers.Builder, unknownBool byte) {
	builder.PrependByteSlot(4, unknownBool, 0)
}
func MovieClipAddChildrenIds(builder *flatbuffers.Builder, childrenIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(childrenIds), 0)
}
func MovieClipStartChildrenIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func MovieClipAddChildrenNameRefIds(builder *flatbuffers.Builder, childrenNameRefIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(childrenNameRefIds), 0)
}
func MovieClipStartChildrenNameRefIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MovieClipAddChildrenBlending(builder *flatbuffers.Builder, childrenBlending flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(childrenBlending), 0)
}
func MovieClipStartChildrenBlendingVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MovieClipAddFrames(builder *flatbuffers.Builder, frames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(frames), 0)
}
func MovieClipStartFramesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func MovieClipAddFrameElementsOffset(builder *flatbuffers.Builder, frameElementsOffset uint32) {
	builder.PrependUint32Slot(9, frameElementsOffset, 4294967295)
}
func MovieClipAddMatrixBankIndex(builder *flatbuffers.Builder, matrixBankIndex uint32) {
	builder.PrependUint32Slot(10, matrixBankIndex, 0)
}
func MovieClipAddScalingGridIndex(builder *flatbuffers.Builder, scalingGridIndex uint32) {
	builder.PrependUint32(scalingGridIndex)
	builder.Slot(11)
}
func MovieClipAddShortFrames(builder *flatbuffers.Builder, shortFrames flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(shortFrames), 0)
}
func MovieClipStartShortFramesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func MovieClipEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
