// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClipModifier struct {
	_tab flatbuffers.Struct
}

func (rcv *MovieClipModifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClipModifier) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MovieClipModifier) Id() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MovieClipModifier) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MovieClipModifier) Type() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *MovieClipModifier) MutateType(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateMovieClipModifier(builder *flatbuffers.Builder, id uint16, type_ byte) flatbuffers.UOffsetT {
	builder.Prep(2, 4)
	builder.Pad(1)
	builder.PrependByte(type_)
	builder.PrependUint16(id)
	return builder.Offset()
}
