// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClipFrame struct {
	_tab flatbuffers.Struct
}

func (rcv *MovieClipFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClipFrame) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MovieClipFrame) UsedTransform() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MovieClipFrame) MutateUsedTransform(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MovieClipFrame) LabelRefId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *MovieClipFrame) MutateLabelRefId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateMovieClipFrame(builder *flatbuffers.Builder, usedTransform uint32, labelRefId uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependUint32(labelRefId)
	builder.PrependUint32(usedTransform)
	return builder.Offset()
}
