// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClipShortFrame struct {
	_tab flatbuffers.Struct
}

func (rcv *MovieClipShortFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClipShortFrame) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MovieClipShortFrame) UsedTransform() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MovieClipShortFrame) MutateUsedTransform(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateMovieClipShortFrame(builder *flatbuffers.Builder, usedTransform uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 2)
	builder.PrependUint16(usedTransform)
	return builder.Offset()
}
