// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClipModifiers struct {
	_tab flatbuffers.Table
}

func GetRootAsMovieClipModifiers(buf []byte, offset flatbuffers.UOffsetT) *MovieClipModifiers {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MovieClipModifiers{}
	x.Init(buf, n+offset)
	return x
}

func FinishMovieClipModifiersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMovieClipModifiers(buf []byte, offset flatbuffers.UOffsetT) *MovieClipModifiers {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MovieClipModifiers{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMovieClipModifiersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MovieClipModifiers) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClipModifiers) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MovieClipModifiers) Modifiers(obj *MovieClipModifier, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MovieClipModifiers) ModifiersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MovieClipModifiersStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MovieClipModifiersAddModifiers(builder *flatbuffers.Builder, modifiers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(modifiers), 0)
}
func MovieClipModifiersStartModifiersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 2)
}
func MovieClipModifiersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
