// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MovieClips struct {
	_tab flatbuffers.Table
}

func GetRootAsMovieClips(buf []byte, offset flatbuffers.UOffsetT) *MovieClips {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MovieClips{}
	x.Init(buf, n+offset)
	return x
}

func FinishMovieClipsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMovieClips(buf []byte, offset flatbuffers.UOffsetT) *MovieClips {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MovieClips{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMovieClipsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MovieClips) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MovieClips) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MovieClips) Movieclips(obj *MovieClip, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MovieClips) MovieclipsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MovieClipsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MovieClipsAddMovieclips(builder *flatbuffers.Builder, movieclips flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(movieclips), 0)
}
func MovieClipsStartMovieclipsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MovieClipsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
