// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import "strconv"

type Precision uint32

const (
	PrecisionNone      Precision = 0
	PrecisionDefault   Precision = 1
	PrecisionTwip      Precision = 2
	PrecisionOptimized Precision = 3
)

var EnumNamesPrecision = map[Precision]string{
	PrecisionNone:      "None",
	PrecisionDefault:   "Default",
	PrecisionTwip:      "Twip",
	PrecisionOptimized: "Optimized",
}

var EnumValuesPrecision = map[string]Precision{
	"None":      PrecisionNone,
	"Default":   PrecisionDefault,
	"Twip":      PrecisionTwip,
	"Optimized": PrecisionOptimized,
}

func (v Precision) String() string {
	if s, ok := EnumNamesPrecision[v]; ok {
		return s
	}
	return "Precision(" + strconv.FormatInt(int64(v), 10) + ")"
}
