// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShapeDrawBitmapCommand struct {
	_tab flatbuffers.Struct
}

func (rcv *ShapeDrawBitmapCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShapeDrawBitmapCommand) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ShapeDrawBitmapCommand) Unk1() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ShapeDrawBitmapCommand) MutateUnk1(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ShapeDrawBitmapCommand) TextureIndex() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *ShapeDrawBitmapCommand) MutateTextureIndex(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *ShapeDrawBitmapCommand) PointsCount() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ShapeDrawBitmapCommand) MutatePointsCount(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *ShapeDrawBitmapCommand) PointsOffset() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *ShapeDrawBitmapCommand) MutatePointsOffset(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateShapeDrawBitmapCommand(builder *flatbuffers.Builder, unk1 uint32, textureIndex uint32, pointsCount uint32, pointsOffset uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependUint32(pointsOffset)
	builder.PrependUint32(pointsCount)
	builder.PrependUint32(textureIndex)
	builder.PrependUint32(unk1)
	return builder.Offset()
}
