// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextField struct {
	_tab flatbuffers.Struct
}

func (rcv *TextField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextField) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TextField) Id() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TextField) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TextField) Unused1() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *TextField) MutateUnused1(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *TextField) FontNameRefId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TextField) MutateFontNameRefId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *TextField) Left() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *TextField) MutateLeft(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *TextField) Top() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *TextField) MutateTop(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func (rcv *TextField) Right() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *TextField) MutateRight(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *TextField) Bottom() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(14))
}
func (rcv *TextField) MutateBottom(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(14), n)
}

func (rcv *TextField) FontColor() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *TextField) MutateFontColor(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *TextField) OutlineColor() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(20))
}
func (rcv *TextField) MutateOutlineColor(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(20), n)
}

func (rcv *TextField) TextRefId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *TextField) MutateTextRefId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func (rcv *TextField) TypographyRefId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(28))
}
func (rcv *TextField) MutateTypographyRefId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(28), n)
}

func (rcv *TextField) Styles() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *TextField) MutateStyles(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func (rcv *TextField) Align() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(33))
}
func (rcv *TextField) MutateAlign(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(33), n)
}

func (rcv *TextField) FontSize() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(34))
}
func (rcv *TextField) MutateFontSize(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(34), n)
}

func (rcv *TextField) Unused2() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(35))
}
func (rcv *TextField) MutateUnused2(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(35), n)
}

func (rcv *TextField) OutlineStrength() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(36))
}
func (rcv *TextField) MutateOutlineStrength(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(36), n)
}

func CreateTextField(builder *flatbuffers.Builder, id uint16, unused1 uint16, fontNameRefId uint32, left int16, top int16, right int16, bottom int16, fontColor uint32, outlineColor uint32, textRefId uint32, typographyRefId uint32, styles byte, align byte, fontSize byte, unused2 byte, outlineStrength uint16) flatbuffers.UOffsetT {
	builder.Prep(4, 40)
	builder.Pad(2)
	builder.PrependUint16(outlineStrength)
	builder.PrependByte(unused2)
	builder.PrependByte(fontSize)
	builder.PrependByte(align)
	builder.PrependByte(styles)
	builder.PrependUint32(typographyRefId)
	builder.PrependUint32(textRefId)
	builder.PrependUint32(outlineColor)
	builder.PrependUint32(fontColor)
	builder.PrependInt16(bottom)
	builder.PrependInt16(right)
	builder.PrependInt16(top)
	builder.PrependInt16(left)
	builder.PrependUint32(fontNameRefId)
	builder.PrependUint16(unused1)
	builder.PrependUint16(id)
	return builder.Offset()
}
