// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextureData struct {
	_tab flatbuffers.Table
}

func GetRootAsTextureData(buf []byte, offset flatbuffers.UOffsetT) *TextureData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextureData{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextureDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextureData(buf []byte, offset flatbuffers.UOffsetT) *TextureData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextureData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextureDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextureData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextureData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextureData) TextureFormat() TextureFormat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TextureFormat(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TextureData) MutateTextureFormat(n TextureFormat) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *TextureData) PixelType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutatePixelType(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *TextureData) Width() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateWidth(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *TextureData) Height() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateHeight(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *TextureData) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TextureData) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TextureData) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TextureData) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TextureData) ExternalTexture() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TextureDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TextureDataAddTextureFormat(builder *flatbuffers.Builder, textureFormat TextureFormat) {
	builder.PrependByteSlot(0, byte(textureFormat), 0)
}
func TextureDataAddPixelType(builder *flatbuffers.Builder, pixelType byte) {
	builder.PrependByteSlot(1, pixelType, 0)
}
func TextureDataAddWidth(builder *flatbuffers.Builder, width uint16) {
	builder.PrependUint16Slot(2, width, 0)
}
func TextureDataAddHeight(builder *flatbuffers.Builder, height uint16) {
	builder.PrependUint16Slot(3, height, 0)
}
func TextureDataAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(data), 0)
}
func TextureDataStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TextureDataAddExternalTexture(builder *flatbuffers.Builder, externalTexture flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(externalTexture), 0)
}
func TextureDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
