// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import "strconv"

type TextFieldStyle byte

const (
	TextFieldStyleunknown_flag3 TextFieldStyle = 1
	TextFieldStylehas_outline   TextFieldStyle = 2
	TextFieldStylebold          TextFieldStyle = 4
	TextFieldStyleitalic        TextFieldStyle = 8
	TextFieldStyleis_multiline  TextFieldStyle = 16
	TextFieldStyleunknown_flag  TextFieldStyle = 32
	TextFieldStyleauto_kern     TextFieldStyle = 64
)

var EnumNamesTextFieldStyle = map[TextFieldStyle]string{
	TextFieldStyleunknown_flag3: "unknown_flag3",
	TextFieldStylehas_outline:   "has_outline",
	TextFieldStylebold:          "bold",
	TextFieldStyleitalic:        "italic",
	TextFieldStyleis_multiline:  "is_multiline",
	TextFieldStyleunknown_flag:  "unknown_flag",
	TextFieldStyleauto_kern:     "auto_kern",
}

var EnumValuesTextFieldStyle = map[string]TextFieldStyle{
	"unknown_flag3": TextFieldStyleunknown_flag3,
	"has_outline":   TextFieldStylehas_outline,
	"bold":          TextFieldStylebold,
	"italic":        TextFieldStyleitalic,
	"is_multiline":  TextFieldStyleis_multiline,
	"unknown_flag":  TextFieldStyleunknown_flag,
	"auto_kern":     TextFieldStyleauto_kern,
}

func (v TextFieldStyle) String() string {
	if s, ok := EnumNamesTextFieldStyle[v]; ok {
		return s
	}
	return "TextFieldStyle(" + strconv.FormatInt(int64(v), 10) + ")"
}
