// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextureSet struct {
	_tab flatbuffers.Table
}

func GetRootAsTextureSet(buf []byte, offset flatbuffers.UOffsetT) *TextureSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextureSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextureSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextureSet(buf []byte, offset flatbuffers.UOffsetT) *TextureSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextureSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextureSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextureSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextureSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextureSet) Lowres(obj *TextureData) *TextureData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TextureData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TextureSet) Highres(obj *TextureData) *TextureData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TextureData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TextureSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TextureSetAddLowres(builder *flatbuffers.Builder, lowres flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(lowres), 0)
}
func TextureSetAddHighres(builder *flatbuffers.Builder, highres flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(highres), 0)
}
func TextureSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
