// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextFields struct {
	_tab flatbuffers.Table
}

func GetRootAsTextFields(buf []byte, offset flatbuffers.UOffsetT) *TextFields {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextFields{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextFieldsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextFields(buf []byte, offset flatbuffers.UOffsetT) *TextFields {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextFields{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextFieldsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextFields) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextFields) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextFields) Textfields(obj *TextField, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 40
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TextFields) TextfieldsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TextFieldsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TextFieldsAddTextfields(builder *flatbuffers.Builder, textfields flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(textfields), 0)
}
func TextFieldsStartTextfieldsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(40, numElems, 4)
}
func TextFieldsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
