// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SC2

import "strconv"

type TextureFormat byte

const (
	TextureFormatUnk1           TextureFormat = 1
	TextureFormatUnk2           TextureFormat = 2
	TextureFormatUnk3           TextureFormat = 4
	TextureFormatKhronosTexture TextureFormat = 8
)

var EnumNamesTextureFormat = map[TextureFormat]string{
	TextureFormatUnk1:           "Unk1",
	TextureFormatUnk2:           "Unk2",
	TextureFormatUnk3:           "Unk3",
	TextureFormatKhronosTexture: "KhronosTexture",
}

var EnumValuesTextureFormat = map[string]TextureFormat{
	"Unk1":           TextureFormatUnk1,
	"Unk2":           TextureFormatUnk2,
	"Unk3":           TextureFormatUnk3,
	"KhronosTexture": TextureFormatKhronosTexture,
}

func (v TextureFormat) String() string {
	if s, ok := EnumNamesTextureFormat[v]; ok {
		return s
	}
	return "TextureFormat(" + strconv.FormatInt(int64(v), 10) + ")"
}
