// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Typing

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ColorTransform struct {
	_tab flatbuffers.Struct
}

func (rcv *ColorTransform) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColorTransform) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ColorTransform) RMul() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ColorTransform) MutateRMul(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ColorTransform) GMul() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *ColorTransform) MutateGMul(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func (rcv *ColorTransform) BMul() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *ColorTransform) MutateBMul(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *ColorTransform) Alpha() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(3))
}
func (rcv *ColorTransform) MutateAlpha(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(3), n)
}

func (rcv *ColorTransform) RAdd() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *ColorTransform) MutateRAdd(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *ColorTransform) GAdd() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(5))
}
func (rcv *ColorTransform) MutateGAdd(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(5), n)
}

func (rcv *ColorTransform) BAdd() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *ColorTransform) MutateBAdd(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func CreateColorTransform(builder *flatbuffers.Builder, rMul byte, gMul byte, bMul byte, alpha byte, rAdd byte, gAdd byte, bAdd byte) flatbuffers.UOffsetT {
	builder.Prep(1, 7)
	builder.PrependByte(bAdd)
	builder.PrependByte(gAdd)
	builder.PrependByte(rAdd)
	builder.PrependByte(alpha)
	builder.PrependByte(bMul)
	builder.PrependByte(gMul)
	builder.PrependByte(rMul)
	return builder.Offset()
}
