// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Typing

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HalfMatrix2x3 struct {
	_tab flatbuffers.Struct
}

func (rcv *HalfMatrix2x3) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HalfMatrix2x3) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *HalfMatrix2x3) A() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *HalfMatrix2x3) MutateA(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *HalfMatrix2x3) B() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *HalfMatrix2x3) MutateB(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *HalfMatrix2x3) C() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *HalfMatrix2x3) MutateC(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *HalfMatrix2x3) D() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *HalfMatrix2x3) MutateD(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *HalfMatrix2x3) Tx() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *HalfMatrix2x3) MutateTx(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *HalfMatrix2x3) Ty() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *HalfMatrix2x3) MutateTy(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func CreateHalfMatrix2x3(builder *flatbuffers.Builder, a int16, b int16, c int16, d int16, tx int16, ty int16) flatbuffers.UOffsetT {
	builder.Prep(2, 12)
	builder.PrependInt16(ty)
	builder.PrependInt16(tx)
	builder.PrependInt16(d)
	builder.PrependInt16(c)
	builder.PrependInt16(b)
	builder.PrependInt16(a)
	return builder.Offset()
}
