// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Typing

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rect struct {
	_tab flatbuffers.Struct
}

func (rcv *Rect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rect) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Rect) Left() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Rect) MutateLeft(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Rect) Top() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Rect) MutateTop(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Rect) Right() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Rect) MutateRight(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *Rect) Bottom() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *Rect) MutateBottom(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateRect(builder *flatbuffers.Builder, left float32, top float32, right float32, bottom float32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependFloat32(bottom)
	builder.PrependFloat32(right)
	builder.PrependFloat32(top)
	builder.PrependFloat32(left)
	return builder.Offset()
}
