// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SCTX

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MipMap struct {
	_tab flatbuffers.Table
}

func GetRootAsMipMap(buf []byte, offset flatbuffers.UOffsetT) *MipMap {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MipMap{}
	x.Init(buf, n+offset)
	return x
}

func FinishMipMapBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMipMap(buf []byte, offset flatbuffers.UOffsetT) *MipMap {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MipMap{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMipMapBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MipMap) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MipMap) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MipMap) Width() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MipMap) MutateWidth(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *MipMap) Height() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MipMap) MutateHeight(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *MipMap) Offset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MipMap) MutateOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *MipMap) Hash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MipMap) HashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MipMap) HashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MipMap) MutateHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MipMapStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MipMapAddWidth(builder *flatbuffers.Builder, width uint16) {
	builder.PrependUint16Slot(0, width, 0)
}
func MipMapAddHeight(builder *flatbuffers.Builder, height uint16) {
	builder.PrependUint16Slot(1, height, 0)
}
func MipMapAddOffset(builder *flatbuffers.Builder, offset uint32) {
	builder.PrependUint32Slot(2, offset, 0)
}
func MipMapAddHash(builder *flatbuffers.Builder, hash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(hash), 0)
}
func MipMapStartHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MipMapEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
