// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SCTX

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextureData struct {
	_tab flatbuffers.Table
}

const TextureDataIdentifier = "SCTX"

func GetRootAsTextureData(buf []byte, offset flatbuffers.UOffsetT) *TextureData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextureData{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextureDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TextureDataIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func TextureDataBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, TextureDataIdentifier)
}

func GetSizePrefixedRootAsTextureData(buf []byte, offset flatbuffers.UOffsetT) *TextureData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextureData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextureDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TextureDataIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedTextureDataBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, TextureDataIdentifier)
}

func (rcv *TextureData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextureData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextureData) Unk1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateUnk1(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TextureData) PixelType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutatePixelType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *TextureData) Width() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateWidth(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *TextureData) Height() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateHeight(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *TextureData) LevelsCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *TextureData) MutateLevelsCount(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *TextureData) Unk3() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateUnk3(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *TextureData) Flags() TextureFlags {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return TextureFlags(rcv._tab.GetUint32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TextureData) MutateFlags(n TextureFlags) bool {
	return rcv._tab.MutateUint32Slot(16, uint32(n))
}

func (rcv *TextureData) TextureLength() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateTextureLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *TextureData) Unk5() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateUnk5(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *TextureData) Unk6() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TextureData) MutateUnk6(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *TextureData) Variants(obj *TextureVariants) *TextureVariants {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TextureVariants)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TextureDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func TextureDataAddUnk1(builder *flatbuffers.Builder, unk1 int32) {
	builder.PrependInt32Slot(0, unk1, 0)
}
func TextureDataAddPixelType(builder *flatbuffers.Builder, pixelType uint32) {
	builder.PrependUint32Slot(1, pixelType, 0)
}
func TextureDataAddWidth(builder *flatbuffers.Builder, width uint16) {
	builder.PrependUint16Slot(2, width, 0)
}
func TextureDataAddHeight(builder *flatbuffers.Builder, height uint16) {
	builder.PrependUint16Slot(3, height, 0)
}
func TextureDataAddLevelsCount(builder *flatbuffers.Builder, levelsCount byte) {
	builder.PrependByteSlot(4, levelsCount, 1)
}
func TextureDataAddUnk3(builder *flatbuffers.Builder, unk3 int32) {
	builder.PrependInt32Slot(5, unk3, 0)
}
func TextureDataAddFlags(builder *flatbuffers.Builder, flags TextureFlags) {
	builder.PrependUint32Slot(6, uint32(flags), 0)
}
func TextureDataAddTextureLength(builder *flatbuffers.Builder, textureLength int32) {
	builder.PrependInt32Slot(7, textureLength, 0)
}
func TextureDataAddUnk5(builder *flatbuffers.Builder, unk5 int32) {
	builder.PrependInt32Slot(8, unk5, 0)
}
func TextureDataAddUnk6(builder *flatbuffers.Builder, unk6 int32) {
	builder.PrependInt32Slot(9, unk6, 0)
}
func TextureDataAddVariants(builder *flatbuffers.Builder, variants flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(variants), 0)
}
func TextureDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
