// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SCTX

import "strconv"

type TextureFlags uint32

const (
	TextureFlagsuse_compression TextureFlags = 1
	TextureFlagsunknown_flag2   TextureFlags = 2
	TextureFlagsunknown_flag3   TextureFlags = 4
	TextureFlagsuse_padding     TextureFlags = 8
)

var EnumNamesTextureFlags = map[TextureFlags]string{
	TextureFlagsuse_compression: "use_compression",
	TextureFlagsunknown_flag2:   "unknown_flag2",
	TextureFlagsunknown_flag3:   "unknown_flag3",
	TextureFlagsuse_padding:     "use_padding",
}

var EnumValuesTextureFlags = map[string]TextureFlags{
	"use_compression": TextureFlagsuse_compression,
	"unknown_flag2":   TextureFlagsunknown_flag2,
	"unknown_flag3":   TextureFlagsunknown_flag3,
	"use_padding":     TextureFlagsuse_padding,
}

func (v TextureFlags) String() string {
	if s, ok := EnumNamesTextureFlags[v]; ok {
		return s
	}
	return "TextureFlags(" + strconv.FormatInt(int64(v), 10) + ")"
}
