// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SCTX

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextureVariants struct {
	_tab flatbuffers.Table
}

func GetRootAsTextureVariants(buf []byte, offset flatbuffers.UOffsetT) *TextureVariants {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextureVariants{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextureVariantsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextureVariants(buf []byte, offset flatbuffers.UOffsetT) *TextureVariants {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextureVariants{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextureVariantsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextureVariants) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextureVariants) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextureVariants) StreamingId(j int) uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *TextureVariants) StreamingIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TextureVariants) MutateStreamingId(j int, n uint32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *TextureVariants) StreamingTextures(obj *StreamingTextureDescriptor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TextureVariants) StreamingTexturesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TextureVariantsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TextureVariantsAddStreamingId(builder *flatbuffers.Builder, streamingId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(streamingId), 0)
}
func TextureVariantsStartStreamingIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TextureVariantsAddStreamingTextures(builder *flatbuffers.Builder, streamingTextures flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(streamingTextures), 0)
}
func TextureVariantsStartStreamingTexturesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TextureVariantsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
