name: 'mirror repo'
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'https://github.com/ClashKingInc/ClashKingAssets.git'
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}